name: DAST - Fastbank Insecure Classwork

on:
  workflow_dispatch:

jobs:
  zap_scan_fastbank:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Start Fastbank app
        working-directory: fastbank_insecure_classwork
        run: |
          npm install
          npm start &
          npx wait-on http://localhost:3000

      - name: Run OWASP ZAP full scan (Fastbank)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "http://host.docker.internal:3000"
          cmd_options: "-a"
