name: DAST - IDOR Lab

on:
  workflow_dispatch:

jobs:
  zap_scan_idor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Start IDOR app
        working-directory: idor
        run: |
          npm install
          npm start &
          # give the app time to boot so ZAP can hit it
          sleep 20

      - name: Run OWASP ZAP full scan (IDOR)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          # app runs at http://localhost:3000
          target: "http://host.docker.internal:3000"
          cmd_options: "-a"
