name: DAST - Canonicalization Example

on:
  workflow_dispatch:

jobs:
  zap_scan_canonicalization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Start Canonicalization app
        working-directory: canonicalization-example
        run: |
          npm install
          npm start &
          npx wait-on http://localhost:3001

      - name: Run OWASP ZAP full scan (Canonicalization)
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: "http://host.docker.internal:3001"
          cmd_options: "-a"
